#!/usr/bin/env python3
"""Generate the Japanese portfolio from index.html and translations/ja.json."""
import html
from html.parser import HTMLParser
import json
from pathlib import Path
import re

ROOT = Path(__file__).resolve().parents[1]
HOME = 'https://shaficse.github.io/'
JAPANESE = HOME + 'jp.html'


class JapanesePage(HTMLParser):
    def __init__(self, strings):
        super().__init__(convert_charrefs=True)
        self.strings = strings
        self.parts = []
        self.raw_tag = None
        self.structured_data = False

    def handle_decl(self, declaration):
        self.parts.append(f'<!{declaration}>')

    def handle_comment(self, comment):
        self.parts.append(f'<!--{comment}-->')

    def handle_starttag(self, tag, attrs):
        attrs = dict(attrs)
        if tag == 'html':
            attrs['lang'] = 'ja'
        if tag in ('script', 'style'):
            self.raw_tag = tag
            self.structured_data = attrs.get('type') == 'application/ld+json'
        for key in ('aria-label', 'alt', 'placeholder', 'content'):
            if key in attrs:
                attrs[key] = self.strings.get(attrs[key], attrs[key])
        if tag == 'link' and attrs.get('rel') == 'canonical':
            attrs['href'] = JAPANESE
        if tag == 'meta' and attrs.get('property') == 'og:url':
            attrs['content'] = JAPANESE
        if tag == 'meta' and attrs.get('property') == 'og:locale':
            attrs['content'] = 'ja_JP'
        if tag == 'a' and attrs.get('hreflang') in ('en', 'ja'):
            attrs.pop('aria-current', None)
            if attrs['hreflang'] == 'ja':
                attrs['aria-current'] = 'page'
            else:
                attrs['aria-label'] = 'English'
        if tag == 'a' and attrs.get('href') in ('cv.html', 'cv.pdf'):
            attrs['hreflang'] = 'en'
        attributes = ''.join(f' {key}' if value is None else f' {key}="{html.escape(value, quote=True)}"' for key, value in attrs.items())
        self.parts.append(f'<{tag}{attributes}>')

    def handle_endtag(self, tag):
        self.parts.append(f'</{tag}>')
        if tag == self.raw_tag:
            self.raw_tag = None
            self.structured_data = False

    def handle_data(self, text):
        if self.structured_data and text.strip():
            data = json.loads(text)
            data['url'] = JAPANESE
            data['inLanguage'] = 'ja'
            self.parts.append(json.dumps(data, ensure_ascii=False))
        elif self.raw_tag:
            self.parts.append(text)
        else:
            normalized = ' '.join(text.split())
            if normalized in self.strings:
                leading = text[:len(text) - len(text.lstrip())]
                trailing = text[len(text.rstrip()):]
                text = leading + self.strings[normalized] + trailing
            self.parts.append(html.escape(text, quote=False))


def build():
    translations = json.loads((ROOT / 'translations/ja.json').read_text())
    parser = JapanesePage(translations['strings'])
    parser.feed((ROOT / 'index.html').read_text())
    page = ''.join(parser.parts)
    page, count = re.subn(r'<div class="about-text">.*?</div>', lambda _: translations['about_html'], page, count=1, flags=re.S)
    if count != 1:
        raise ValueError('Expected one About text block; update the Japanese template.')
    # Preserve searchable, published paper titles in their original language.
    for title in translations['english_titles']:
        escaped = html.escape(title, quote=False)
        page = page.replace('>' + escaped + '<', '><span lang="en">' + escaped + '</span><')
    page = page.replace('<html lang="ja">', '<!-- Generated by scripts/build_japanese.py; edit index.html and translations/ja.json. -->\n<html lang="ja">', 1)
    (ROOT / 'jp.html').write_text(page)
    print('Generated jp.html')


if __name__ == '__main__':
    build()
